fixed_size:
  chunk_size: 512
  overlap: 50

passage:
  passage_length: 10

text_tiling:
  w: 20
  k: 10
  similarity_method: block_comparison
  stopwords: []
  smoothing_method: default
  smoothing_width: 2
  smoothing_rounds: 1
  cutoff_policy: hc
  demo_mode: false
