# parametry sprawdzić jak sobie radzi przez clarin api i z jaki kontekst modelu. w papierze nrak info, gpt-4 był i bardzo krotkie dokumnenty
# a my mamy tez długie
model: "Qwen/Qwen3.5-4B"          # Model HF do generowania propozycji
max_context: 6000               # Maksymalna liczba tokenów, jeśli nie podano, użyje domyślnych
max_new_tokens: 3000             # Maksymalna liczba tokenów do wygenerowania w oknie
batch_size: 4                    # Batch size dla pipeline HF
overlap_ratio: 0.05             # Overlap między sliding window (10%)
prompt_overhead_tokens: 700      # Szacowana liczba tokenów w prompt
temperature: 0.0                 # Deterministyczna generacja